// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvmqWDxHrSZ4zNHVN9uKHxiD8c9ZthaZ0',
    appId: '1:340043362765:web:e8e2b94ce24b44aa789484',
    messagingSenderId: '340043362765',
    projectId: 'ebooks-7be44',
    authDomain: 'ebooks-7be44.firebaseapp.com',
    databaseURL: 'https://ebooks-7be44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ebooks-7be44.appspot.com',
    measurementId: 'G-WZ304JZK0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClQa6zMPhvxG0L1YZgvQjThInwfDmGxiM',
    appId: '1:340043362765:android:abbac5c671c4335f789484',
    messagingSenderId: '340043362765',
    projectId: 'ebooks-7be44',
    databaseURL: 'https://ebooks-7be44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ebooks-7be44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmqnKX1GexkcYE1d8k3O-5H1lUw9IDPLc',
    appId: '1:340043362765:ios:0f3e139554426ce6789484',
    messagingSenderId: '340043362765',
    projectId: 'ebooks-7be44',
    databaseURL: 'https://ebooks-7be44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ebooks-7be44.appspot.com',
    iosClientId: '340043362765-c8hj31km6vc1pqoa0aodq2bh3d0rrit5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebooksUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmqnKX1GexkcYE1d8k3O-5H1lUw9IDPLc',
    appId: '1:340043362765:ios:0f3e139554426ce6789484',
    messagingSenderId: '340043362765',
    projectId: 'ebooks-7be44',
    databaseURL: 'https://ebooks-7be44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ebooks-7be44.appspot.com',
    iosClientId: '340043362765-c8hj31km6vc1pqoa0aodq2bh3d0rrit5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebooksUp',
  );
}
